-- Tata Motors Financial Analysis Project
-- MySQL Workbench-ready database and table setup script
-- Run this file FIRST in MySQL Workbench.

CREATE DATABASE IF NOT EXISTS tata_motors_financial_analysis;
USE tata_motors_financial_analysis;

SET SQL_SAFE_UPDATES = 0;

DROP TABLE IF EXISTS `income_statement`;
CREATE TABLE `income_statement` (
    `financial_year` VARCHAR(50) NOT NULL,
    `source_report` TEXT,
    `unit` VARCHAR(50),
    `revenue` DECIMAL(18,2) NULL,
    `other_operating_revenues` DECIMAL(18,2) NULL,
    `total_revenue_from_operations` DECIMAL(18,2) NULL,
    `other_income` DECIMAL(18,2) NULL,
    `total_income` DECIMAL(18,2) NULL,
    `cost_of_materials_consumed` DECIMAL(18,2) NULL,
    `basis_adjustment_on_hedge_accounted_derivatives` DECIMAL(18,2) NULL,
    `purchase_of_products_for_sale` DECIMAL(18,2) NULL,
    `changes_in_inventories` DECIMAL(18,2) NULL,
    `employee_benefits_expense` DECIMAL(18,2) NULL,
    `finance_costs` DECIMAL(18,2) NULL,
    `ccp_share_fair_value_gain_loss` DECIMAL(18,2) NULL,
    `foreign_exchange_gain_loss_net` DECIMAL(18,2) NULL,
    `depreciation_and_amortisation_expense` DECIMAL(18,2) NULL,
    `product_development_engineering_expenses` DECIMAL(18,2) NULL,
    `other_expenses` DECIMAL(18,2) NULL,
    `amount_transferred_to_capital_and_other_account` DECIMAL(18,2) NULL,
    `total_expenses` DECIMAL(18,2) NULL,
    `profit_before_share_exceptional_items_and_tax` DECIMAL(18,2) NULL,
    `share_of_profit_loss_equity_accounted_investees` DECIMAL(18,2) NULL,
    `profit_before_exceptional_items_and_tax` DECIMAL(18,2) NULL,
    `exceptional_items_loss_net` DECIMAL(18,2) NULL,
    `profit_before_tax` DECIMAL(18,2) NULL,
    `current_tax` DECIMAL(18,2) NULL,
    `deferred_tax` DECIMAL(18,2) NULL,
    `total_tax_expense_credit` DECIMAL(18,2) NULL,
    `profit_from_continuing_operations` DECIMAL(18,2) NULL,
    `profit_loss_from_discontinued_operations` DECIMAL(18,2) NULL,
    `profit_for_year` DECIMAL(18,2) NULL,
    `profit_attributable_to_shareholders` DECIMAL(18,2) NULL,
    `profit_attributable_to_non_controlling_interests` DECIMAL(18,2) NULL,
    `notes` TEXT,
    PRIMARY KEY (`financial_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `balance_sheet`;
CREATE TABLE `balance_sheet` (
    `financial_year` VARCHAR(50) NOT NULL,
    `fiscal_year_end` VARCHAR(50),
    `source_report` TEXT,
    `unit` VARCHAR(50),
    `property_plant_and_equipment` DECIMAL(18,2) NULL,
    `capital_work_in_progress` DECIMAL(18,2) NULL,
    `right_of_use_assets` DECIMAL(18,2) NULL,
    `goodwill` DECIMAL(18,2) NULL,
    `other_intangible_assets` DECIMAL(18,2) NULL,
    `intangible_assets_under_development` DECIMAL(18,2) NULL,
    `investment_in_equity_accounted_investees` DECIMAL(18,2) NULL,
    `non_current_investments` DECIMAL(18,2) NULL,
    `non_current_finance_receivables` DECIMAL(18,2) NULL,
    `non_current_loans` DECIMAL(18,2) NULL,
    `non_current_other_financial_assets` DECIMAL(18,2) NULL,
    `deferred_tax_assets_net` DECIMAL(18,2) NULL,
    `non_current_tax_assets_net` DECIMAL(18,2) NULL,
    `other_non_current_assets` DECIMAL(18,2) NULL,
    `total_non_current_assets` DECIMAL(18,2) NULL,
    `inventories` DECIMAL(18,2) NULL,
    `current_investments` DECIMAL(18,2) NULL,
    `trade_receivables` DECIMAL(18,2) NULL,
    `cash_and_cash_equivalents` DECIMAL(18,2) NULL,
    `bank_balances_other_than_cash` DECIMAL(18,2) NULL,
    `current_finance_receivables` DECIMAL(18,2) NULL,
    `current_loans` DECIMAL(18,2) NULL,
    `current_other_financial_assets` DECIMAL(18,2) NULL,
    `current_tax_assets_net` DECIMAL(18,2) NULL,
    `other_current_assets` DECIMAL(18,2) NULL,
    `total_current_assets_excluding_held_for_sale` DECIMAL(18,2) NULL,
    `assets_classified_as_held_for_sale` DECIMAL(18,2) NULL,
    `total_assets` DECIMAL(18,2) NULL,
    `equity_share_capital` DECIMAL(18,2) NULL,
    `other_equity` DECIMAL(18,2) NULL,
    `equity_attributable_to_owners` DECIMAL(18,2) NULL,
    `non_controlling_interests` DECIMAL(18,2) NULL,
    `total_equity` DECIMAL(18,2) NULL,
    `non_current_borrowings` DECIMAL(18,2) NULL,
    `non_current_lease_liabilities` DECIMAL(18,2) NULL,
    `ccps_liability_portion` DECIMAL(18,2) NULL,
    `non_current_other_financial_liabilities` DECIMAL(18,2) NULL,
    `non_current_provisions` DECIMAL(18,2) NULL,
    `deferred_tax_liabilities_net` DECIMAL(18,2) NULL,
    `other_non_current_liabilities` DECIMAL(18,2) NULL,
    `total_non_current_liabilities` DECIMAL(18,2) NULL,
    `current_borrowings` DECIMAL(18,2) NULL,
    `current_lease_liabilities` DECIMAL(18,2) NULL,
    `trade_payables_micro_small_enterprises` DECIMAL(18,2) NULL,
    `trade_payables_others` DECIMAL(18,2) NULL,
    `acceptances` DECIMAL(18,2) NULL,
    `current_other_financial_liabilities` DECIMAL(18,2) NULL,
    `other_current_liabilities` DECIMAL(18,2) NULL,
    `current_provisions` DECIMAL(18,2) NULL,
    `current_tax_liabilities_net` DECIMAL(18,2) NULL,
    `liabilities_associated_with_assets_held_for_sale` DECIMAL(18,2) NULL,
    `total_current_liabilities` DECIMAL(18,2) NULL,
    `total_equity_and_liabilities` DECIMAL(18,2) NULL,
    `notes` TEXT,
    PRIMARY KEY (`financial_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `cash_flow_statement`;
CREATE TABLE `cash_flow_statement` (
    `financial_year` VARCHAR(50) NOT NULL,
    `year_end` VARCHAR(50),
    `profit_for_year` DECIMAL(18,2) NULL,
    `depreciation_and_amortisation` DECIMAL(18,2) NULL,
    `cash_flow_before_working_capital_changes` DECIMAL(18,2) NULL,
    `cash_generated_from_operations` DECIMAL(18,2) NULL,
    `income_tax_paid` DECIMAL(18,2) NULL,
    `net_cash_from_operating_activities` DECIMAL(18,2) NULL,
    `payments_for_property_plant_equipment` DECIMAL(18,2) NULL,
    `payments_for_intangible_assets` DECIMAL(18,2) NULL,
    `total_capex_payments` DECIMAL(18,2) NULL,
    `proceeds_from_sale_of_property_plant_equipment` DECIMAL(18,2) NULL,
    `interest_received` DECIMAL(18,2) NULL,
    `dividend_received` DECIMAL(18,2) NULL,
    `net_cash_used_in_investing_activities` DECIMAL(18,2) NULL,
    `proceeds_from_long_term_borrowings` DECIMAL(18,2) NULL,
    `repayment_of_long_term_borrowings` DECIMAL(18,2) NULL,
    `proceeds_from_short_term_borrowings` DECIMAL(18,2) NULL,
    `repayment_of_short_term_borrowings` DECIMAL(18,2) NULL,
    `interest_paid` DECIMAL(18,2) NULL,
    `dividend_paid` DECIMAL(18,2) NULL,
    `net_cash_from_financing_activities` DECIMAL(18,2) NULL,
    `net_increase_decrease_cash_equivalents` DECIMAL(18,2) NULL,
    `opening_cash_and_cash_equivalents` DECIMAL(18,2) NULL,
    `cash_reclassified_or_disposed` DECIMAL(18,2) NULL,
    `effect_of_fx_on_cash` DECIMAL(18,2) NULL,
    `closing_cash_and_cash_equivalents` DECIMAL(18,2) NULL,
    `auto_free_cash_flow` DECIMAL(18,2) NULL,
    `source_report` TEXT,
    `unit` VARCHAR(50),
    `notes` TEXT,
    PRIMARY KEY (`financial_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `financial_ratios`;
CREATE TABLE `financial_ratios` (
    `financial_year` VARCHAR(50) NOT NULL,
    `revenue_from_operations_cr` DECIMAL(18,2) NULL,
    `total_income_cr` DECIMAL(18,2) NULL,
    `profit_before_tax_cr` DECIMAL(18,2) NULL,
    `profit_after_tax_cr` DECIMAL(18,2) NULL,
    `total_assets_cr` DECIMAL(18,2) NULL,
    `total_equity_cr` DECIMAL(18,2) NULL,
    `total_liabilities_cr` DECIMAL(18,2) NULL,
    `current_assets_cr` DECIMAL(18,2) NULL,
    `current_liabilities_cr` DECIMAL(18,2) NULL,
    `cash_and_cash_equivalents_cr` DECIMAL(18,2) NULL,
    `current_investments_cr` DECIMAL(18,2) NULL,
    `total_borrowings_cr` DECIMAL(18,2) NULL,
    `net_cash_from_operating_activities_cr` DECIMAL(18,2) NULL,
    `auto_free_cash_flow_cr` DECIMAL(18,2) NULL,
    `capex_payments_cr` DECIMAL(18,2) NULL,
    `net_profit_margin_pct` DECIMAL(18,2) NULL,
    `pbt_margin_pct` DECIMAL(18,2) NULL,
    `expense_to_income_ratio_pct` DECIMAL(18,2) NULL,
    `return_on_assets_pct` DECIMAL(18,2) NULL,
    `return_on_equity_pct` DECIMAL(18,2) NULL,
    `asset_turnover_ratio` DECIMAL(18,2) NULL,
    `current_ratio` DECIMAL(18,2) NULL,
    `quick_ratio` DECIMAL(18,2) NULL,
    `cash_ratio` DECIMAL(18,2) NULL,
    `working_capital_cr` DECIMAL(18,2) NULL,
    `debt_to_equity_ratio` DECIMAL(18,2) NULL,
    `debt_ratio` DECIMAL(18,2) NULL,
    `operating_cash_flow_margin_pct` DECIMAL(18,2) NULL,
    `free_cash_flow_margin_pct` DECIMAL(18,2) NULL,
    `capex_to_revenue_pct` DECIMAL(18,2) NULL,
    `source_income_statement` TEXT,
    `source_balance_sheet` TEXT,
    `source_cash_flow` TEXT,
    `notes` TEXT,
    PRIMARY KEY (`financial_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


SHOW TABLES;
